#!/usr/bin/env bash

# make passwordless sudo

sudo sed -i /etc/sudoers -re 's/^%sudo.*/%sudo   ALL=(ALL:ALL) NOPASSWD: ALL/g'

sudo apt update && apt install -y make build-essential libssl-dev zlib1g-dev \
    libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev \
    libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python3-openssl git

if ! command -v pyenv &> /dev/null; then
    curl -fsSL https://pyenv.run | bash
    echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
    export PYENV_ROOT="$HOME/.pyenv"
    echo '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
    [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
    echo 'eval "$(pyenv init - bash)"' >> ~/.bashrc
    eval "$(pyenv init - bash)"
    pyenv install 3
    pyenv global 3
    pip install ansible
fi
ansible-pull -U https://github.com/rhildred/ansible-vscode.git
